backend:
  name: github
  repo: oo-infty/blog
  branch: master

media_folder: "assets/images"
public_folder: "/images"

collections:
  - name: "post"
    label: "Post"
    folder: "content/posts"
    slug: "{{slug}}"
    create: true
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "date", label: "Date", widget: "datetime" }
      - { name: "draft", label: "Draft", widget: "boolean", default: true }
      - { name: "body", label: "Body", widget: "markdown" }
